# Generated by Django 5.2.5 on 2025-09-01 02:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
        migrations.AlterModelTable(
            name="userdevice",
            table="user_device",
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="user_profile",
        ),
        migrations.AlterModelTable(
            name="usersegment",
            table="user_segment",
        ),
    ]
