# Generated by Django 5.2.5 on 2025-09-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_table_alter_userdevice_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersegment",
            name="display_name",
            field=models.CharField(
                default="",
                help_text="The display name for the segment in the app or admin.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="usersegment",
            name="name",
            field=models.CharField(
                choices=[
                    ("user_standard", "Usuario Estándar"),
                    ("new_user", "Usuario Nuevo"),
                    ("frequent_user", "Usuario Frecuente"),
                ],
                help_text="The unique identifier for the segment.",
                max_length=50,
                unique=True,
            ),
        ),
    ]
