
services:
  db_postgresql_local:
    image: postgres:14
    container_name: flash_promo_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      # data persistence
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: flash_promo_redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"]

volumes:
  postgres_data: