# Generated by Django 5.2.5 on 2025-09-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='reserveditem',
            table='reserved_item',
        ),
    ]
