# Generated by Django 5.2.5 on 2025-08-31 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashPromo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("special_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "radius",
                    models.PositiveIntegerField(
                        default=2, help_text="The distance is in km"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flash_promos",
                        to="stores.storeproduct",
                    ),
                ),
                (
                    "user_segments",
                    models.ManyToManyField(
                        related_name="flash_promos", to="users.usersegment"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["start_time", "end_time"],
                        name="flash_promo_start_t_10cfe4_idx",
                    )
                ],
            },
        ),
    ]
