# Generated by Django 5.2.5 on 2025-09-01 02:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flash_promos", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="flashpromo",
            new_name="flash_promo_start_t_79bdaf_idx",
            old_name="flash_promo_start_t_10cfe4_idx",
        ),
        migrations.AlterModelTable(
            name="flashpromo",
            table="flash_promo",
        ),
    ]
