# Generated by Django 5.2.5 on 2025-09-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "flash_promos",
            "0002_rename_flash_promo_start_t_10cfe4_idx_flash_promo_start_t_79bdaf_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="flashpromo",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
