# Generated by Django 5.2.5 on 2025-09-01 02:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table="product",
        ),
        migrations.AlterModelTable(
            name="store",
            table="store",
        ),
        migrations.AlterModelTable(
            name="storeproduct",
            table="store_product",
        ),
    ]
